"""create table

Revision ID: 142ebe157b75
Revises: 052c30803429
Create Date: 2026-01-29 16:33:46.545718

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '142ebe157b75'
down_revision: Union[str, Sequence[str], None] = '052c30803429'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teachers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('middle_name', sa.String(length=100), nullable=True),
    sa.Column('photo', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('users', 'patronymic')
    op.drop_column('users', 'class_name')
    op.drop_column('users', 'qualification')
    op.drop_column('users', 'study_year')
    op.drop_column('users', 'birthday')
    op.drop_column('users', 'location')
    op.drop_column('users', 'first_name')
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'passport_id')
    op.drop_column('users', 'subjects')
    op.drop_column('users', 'training_date')
    op.drop_column('users', 'role')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', postgresql.ENUM('OWNER', 'TEACHER', 'STUDENT', name='userrole'), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('training_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('subjects', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('passport_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('last_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('first_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('birthday', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('study_year', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('qualification', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('class_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('patronymic', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_table('teachers')
    # ### end Alembic commands ###
