"""create user

Revision ID: 6ef5c6bdd0c4
Revises: 1a7c5f212175
Create Date: 2025-11-20 18:29:09.662772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ef5c6bdd0c4'
down_revision: Union[str, Sequence[str], None] = '1a7c5f212175'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('first_name', sa.String(), nullable=False))
    op.add_column('users', sa.Column('last_name', sa.String(), nullable=False))
    op.add_column('users', sa.Column('patronymic', sa.String(), nullable=True))
    op.add_column('users', sa.Column('passport_id', sa.String(), nullable=False))
    op.add_column('users', sa.Column('birthday', sa.DateTime(), nullable=False))
    op.add_column('users', sa.Column('location', sa.String(), nullable=True))
    op.add_column('users', sa.Column('study_year', sa.String(), nullable=True))
    op.add_column('users', sa.Column('class_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('subjects', sa.JSON(), nullable=True))
    op.add_column('users', sa.Column('qualification', sa.String(), nullable=True))
    op.add_column('users', sa.Column('training_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'training_date')
    op.drop_column('users', 'qualification')
    op.drop_column('users', 'subjects')
    op.drop_column('users', 'class_name')
    op.drop_column('users', 'study_year')
    op.drop_column('users', 'location')
    op.drop_column('users', 'birthday')
    op.drop_column('users', 'passport_id')
    op.drop_column('users', 'patronymic')
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    # ### end Alembic commands ###
